[chg] revert kiosk changes

diff --git a/OPSI/preinst b/OPSI/preinst
--- a/OPSI/preinst
+++ b/OPSI/preinst
@@ -8,6 +8,8 @@
 #   CLIENT_DATA_DIR: directory where client data will be installed
 #
 
+if 
+
 TMP_DIR=${CLIENT_DATA_DIR}/../${PRODUCT_ID}.tmp
 
 if [ -d $TMP_DIR ]; then
@@ -30,7 +32,7 @@ if [ -d $CLIENT_DATA_DIR ]; then
 	done
 fi
 
-
+: '
 #******************************************
 # START opsi-client-kiosk migration 
 #******************************************
@@ -41,9 +43,30 @@ fi
 KIOSK_IN_AGENT_DIR=${CLIENT_DATA_DIR}/files/opsi/opsiclientkiosk
 OCK_DIR=${CLIENT_DATA_DIR}/../opsi-client-kiosk
 
+# Check if Kiosk is active on a client
+EMPTY=""
+SERVER_CONFIG_ACTIVE=`opsi-admin -dS method config_getObjects [] '{"id":"software-on-demand.active", "defaultValues":[true]}'`
+if [ "${SERVER_CONFIG_ACTIVE}" != "${EMPTY}" ] ; then
+	KIOSK_ACTIVE=true
+else
+	CLIENTS_CONFIG_ACTIVE=`opsi-admin -dS method configState_getObjects [] '{"configId":"software-on-demand.active","values":"[true]"}'`
+	if [ "${CLIENTS_CONFIG_ACTIVE}" != "${EMPTY}" ] ; then
+		KIOSK_ACTIVE=true
+	else
+		KIOSK_ACTIVE=false
+	fi
+fi
+
+#abort if the kiosk is active on a client but the opsi-client-package is not installed on the depot
+# otherwise the kiosk is not more availablere
+if [ $KIOSK_ACTIVE ] && [ ! -d $OCK_DIR ] ; then
+	echo "Installation abort. Please first install the opsi-client-kiosk package on the depot"
+	exit 1
+fi
+	
 # Only migrate if kiosk exists in former client-agent 
 # and the kiosk package was not installed on depot before
-if [ -d $KIOSK_IN_AGENT_DIR ] && [ ! -d $OCK_DIR ]; then
+if [ -d $KIOSK_IN_AGENT_DIR ] && [ ! -d $OCK_DIR ] ; then
 	#opsi-client-kiosk dirs
 	OCK_APP_DIR=${OCK_DIR}/files/app
 	OCK_MIGRATION_DIR=${OCK_DIR}/migration
@@ -65,20 +88,24 @@ if [ -d $KIOSK_IN_AGENT_DIR ] && [ ! -d $OCK_DIR ]; then
 	[ ! -d $OCK_MIGRATION_DIR ] && mkdir -p $OCK_MIGRATION_DIR
 	[ ! -d $OCK_APP_DIR ] && mkdir -p $OCK_APP_DIR
 	
+	#opsi-admin -d method createProduct "localboot" "opsi-client-kiosk" "Opsi Client Kiosk" "4.1.0.0" "1"
 	# Handle properties
 	STARTMENUE_ENTRY=`opsi-admin -d method productPropertyState_getObjects '[]' '{"productId":"opsi-client-agent", "propertyId":"kiosk_startmenue_entry"}'`
 	STARTMENUE_ENTRY=`echo $STARTMENUE_ENTRY | sed s/opsi-client-agent/opsi-client-kiosk/g`
 	STARTMENUE_ENTRY=`echo $STARTMENUE_ENTRY | sed s/kiosk_startmenue_entry/startmenue_entry/g`
+	#opsi-admin -d method productPropertyState_updateObjects "${STARTMENUE_ENTRY}"
 	echo $STARTMENUE_ENTRY > ${OCK_MIGRATION_DIR}/startmenue_entry.json 
 	
 	STARTMENUE_FOLDER=`opsi-admin -d method productPropertyState_getObjects '[]' '{"productId":"opsi-client-agent", "propertyId":"kiosk_startmenue_folder"}'`
 	STARTMENUE_FOLDER=`echo $STARTMENUE_FOLDER | sed s/opsi-client-agent/opsi-client-kiosk/g`
 	STARTMENUE_FOLDER=`echo $STARTMENUE_FOLDER | sed s/kiosk_startmenue_folder/startmenue_folder/g`
+	#opsi-admin -d method productPropertyState_updateObjects "${STARTMENUE_FOLDER}"
 	echo $STARTMENUE_FOLDER > ${OCK_MIGRATION_DIR}/startmenue_folder.json
 	
 	DESKTOP_ICON=`opsi-admin -d method productPropertyState_getObjects '[]' '{"productId":"opsi-client-agent", "propertyId":"kiosk_desktop_icon"}'`
 	DESKTOP_ICON=`echo $DESKTOP_ICON | sed s/opsi-client-agent/opsi-client-kiosk/g`
 	DESKTOP_ICON=`echo $DESKTOP_ICON | sed s/kiosk_desktop_icon/desktop_icon/g`
+	#opsi-admin -d method productPropertyState_updateObjects "${DESKTOP_ICON}"
 	echo $DESKTOP_ICON > ${OCK_MIGRATION_DIR}/desktop_icon.json
 
 	if [ $OCK_CUSTOM_IN_AGENT_DIR ]; then
@@ -111,5 +138,6 @@ fi
 #		done
 #	done
 #fi
+'
 
 exit 0
